# Generated by Django 2.1.5 on 2019-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nomb', models.CharField(max_length=30)),
                ('carrera', models.CharField(db_column='Carrera', max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteTipo',
            fields=[
                ('tcliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tcliente_nomb', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cliente_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nomb', models.CharField(max_length=30)),
                ('cedula', models.IntegerField()),
                ('fecha_registro', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('forma_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago_descrip', models.CharField(max_length=30)),
                ('forma_pago_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroMovimiento',
            fields=[
                ('no_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.CharField(max_length=30)),
                ('monto', models.FloatField()),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'registro_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioFacturable',
            fields=[
                ('servicio_fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_fact_descrip', models.CharField(max_length=30)),
                ('servicio_fact_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'servicio_facturable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TandaLabor',
            fields=[
                ('tanda_labor_id', models.AutoField(primary_key=True, serialize=False)),
                ('tanda_labor_nomb', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tanda_labor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipo_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc_descrip', models.CharField(max_length=30)),
                ('tipo_doc_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
    ]
