# Generated by Django 2.1.5 on 2019-02-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Mysql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
    ]
